apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db
  name: db
  namespace: vote
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: 80
    targetPort: 5432
  selector:
    app: db
