apiVersion: v1
kind: Pod
metadata:
  name: votingapp-pod
  labels:
    name: vote-pod
    app: demo-voting-app 
spec:
  containers:
  - name: redis
    image: mshaibek/voting-app_vote:1.0
    ports: 80 
    - containerPort: 6379
      name: vote


---

apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    name: vote-pod
    app: demo-voting-app


