apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-service
    name: redis
    namespace: votepod
spec:
  type: ClusterIP
  ports:
  - name: "redis-service"
    port: 80
    targetPort: 6379
  selector:
    app: redis
